name=BlueCrypt
version=1.0.0
author=Aadruta PB
maintainer=Aadruta PB <aadrutapb@gmail.com>
sentence=A custom encryption and decryption library.
paragraph=This library uses custom modular arithmetic loops to lock and unlock data.
category=Data Processing
url=https://github.com
architectures=*
